services:
  # Database
  db:
    image: postgres:16-alpine
    container_name: upvote_db
    restart: unless-stopped
    ports:
      - "5433:5432" # Оставляем для дебага если надо, но лучше убрать в проде
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: upvote
    networks:
      - upvote_internal

  # Node.js — отправляет AA-транзакции
  tx-service:
    build:
      context: ./tx-service
    container_name: upvote_tx_service
    restart: unless-stopped
    expose:
      - "3010"
    env_file:
      - ./tx-service/.env
    environment:
      INTERNAL_SECRET: ce1db455f060cf2d3cc5e64a6768e4bacf6ec793cb3bf3fc9b88a978ddaaec7a
      RPC_URL: https://api.mainnet.abs.xyz
    networks:
      - upvote_internal

  # Python FastAPI — очереди, расписание, база, auth
  backend:
    build:
      context: ./backend
    container_name: upvote_backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://user:pass@db:5432/upvote
      ENCRYPTION_KEY: Scc_vD2XAtMBhS7kA_SeGqw0pYgNgIJNwUBND-2SL5E=
      API_SECRET_KEY: b584952056b7bf2adcab58cd46a5560fbd6c5ec3ef6b805d74d7924187b632c1
      TX_SERVICE_SECRET: ce1db455f060cf2d3cc5e64a6768e4bacf6ec793cb3bf3fc9b88a978ddaaec7a
      TX_SERVICE_URL: http://tx-service:3010
      CORS_ORIGINS: "*"
    depends_on:
      - db
      - tx-service
    networks:
      - upvote_internal

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
    container_name: upvote_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - upvote_internal

networks:
  upvote_internal:
    driver: bridge
